language: node_js
sudo: false
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
dist: trusty
script:
- npm run lint
- npm test
- npm run build
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_KEY
  skip_cleanup: true
  on:
    tags: true