language: node_js
sudo: false
node_js:
  - 8
  - 10
cache:
  directories:
    - "node_modules"
dist: trusty
before_install:
  - npm install -g npm
  - npm install -g greenkeeper-lockfile@1
  - npm install -g codecov
before_script: greenkeeper-lockfile-update
script:
  - npm run lint
  - npm run test:coverage
  - npm run build
# Only the node version 8 job will upload the lockfile
after_script: greenkeeper-lockfile-upload
after_success:
  - npm run test:coverage-report
  - codecov
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_KEY
  skip_cleanup: true
  on:
    node: 8
    tags: true